### ISSUE TITLE
problem in step1

### ISSUE THREAD

**Issue by Yyeserin** [carolindahms/TreeMix#1]
Hi!

I am trying to run the software in linux using the code below just for trial. I am sure that phylip exe works fine. 

_sh ./Step1_TreeMix.sh populations.treemix.gz 1 3 noRoot 3 /home/yeserin/snphylo/phylip-3.697/exe/consense 3spine 1  3 3_

I keep getting the error pasted to the end.

I checked the line 49 in Step1_TreeMix.sh: 
__seq 1 $nboot | parallel -j$ncore dowork {} $infile $blockk $outname > $outname"_logfile_constree_bootrep.log"__

Is the problem related to the core usage, or something else?
 
I can provide more information if needed. I appreciate any help/suggestions a lot!

Best,
Yeserin.

**ERROR**

_**** Running TreeMix ****
./Step1_TreeMix.sh: line 49: parallel: command not found
**** Running TreeMix: DONE ****
gzip: bootstrap/3spine_constree_bootrep_1.treeout.gz: No such file or directory
gzip: bootstrap/3spine_constree_bootrep_2.treeout.gz: No such file or directory
gzip: bootstrap/3spine_constree_bootrep_3.treeout.gz: No such file or directory
***** Bootstrap procedure: DONE *****
***** Phylip - consensus tree construction: START *****
***** Phylip - consensus tree construction: DONE *****
**** Running TreeMix with consensus tree adding 1 to 3 migration edges****
./Step1_TreeMix.sh: line 116: treemix: command not found
./Step1_TreeMix.sh: line 116: treemix: command not found
./Step1_TreeMix.sh: line 116: treemix: command not found
./Step1_TreeMix.sh: line 116: treemix: command not found
./Step1_TreeMix.sh: line 116: treemix: command not found
./Step1_TreeMix.sh: line 116: treemix: command not found
./Step1_TreeMix.sh: line 116: treemix: command not found
./Step1_TreeMix.sh: line 116: treemix: command not found
./Step1_TreeMix.sh: line 116: treemix: command not found
**** TreeMix - Bootstrap Analysis with migrations: DONE ****_

**Comment by Prashantevo** [comment]
I think it is the problem with your parallel and treemix.  provide a path as export PATH=$PATH:/home/directory/where/parallel/is and the same for the actual tree mix tool export PATH=$PATH:/home/directory/where/treemix/is. Then run step 1.

**Comment by Yyeserin** [comment]
Hi again,

My problem seems to be solved now after calling parallel and treemix packages. Thank for the advice!
