### ISSUE TITLE
maxLL little bug

### ISSUE THREAD

**Issue by konopinski** [carolindahms/TreeMix#11]
Hi,
I could not run the shell scripts because of some problem with parallel (Ubuntu 22.04.4 LTS) but it's not something I wanted to write. I found a small bug in `maxLL` function which affects the function only in rare occasions when there is only a single best tree. In the function definition (https://github.com/carolindahms/TreeMix/blob/d3cf65ebbacc410e22cd69183ad5f9c79e247f12/TreeMix_functions.R) in line 24 variable `uniqueT` is called that is defined in the line 34. It is enough to move this line before `if` starts (should be line 23).
Cheers
Maciek

**Comment by carolindahms** [comment]
Noted, thanks Maciek!
